#!/bin/bash
# Git Commit Announcer
# Speaks commit confirmations - add as post-commit hook
#
# Usage: Copy to .git/hooks/post-commit and make executable

TTS_PATH="/path/to/tts/tts"  # EDIT THIS PATH

COMMIT_MSG=$(git log -1 --pretty=%B | head -1)
SHORT_HASH=$(git rev-parse --short HEAD)

"$TTS_PATH" "Committed: $COMMIT_MSG"
